### ISSUE TITLE
[BUG] v0.32.0 - Cannot find module '@observerly/*' or its corresponding type declarations.

### ISSUE THREAD

**Issue by EloxFire** [observerly/astrometry#171]
When importing methods from the package in 0.32.0 this error shows up. Seems like the package has an issue exporting its components.

```
import { EquatorialCoordinate, convertEquatorialToHorizontal } from "@observerly/astrometry";
```
![image](https://github.com/observerly/astrometry/assets/43670144/ef4f7065-53d2-4eb7-a37e-fa87423ceba8)
___

**Workaround :**
- Use Observerly/astrometry V0.31.0, it works like a charm 👍🏻

**Comment by michealroberts** [comment]
Hey @EloxFire , are you able to share with me your `tsconfig.json` file ...

**Comment by EloxFire** [comment]
Hey ! Of course, this is my tsconfig :

```javascript
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

I just noticed I have my target in es5, is es6 mandatory ?

**Comment by michealroberts** [comment]
@EloxFire Nope, it should be fine for any ES version. I have just bumped a few fixes to the `package.json`, could you try installing version v0.33.2 for me and letting me know. 🙏

**Comment by EloxFire** [comment]
Testing now !

**Comment by EloxFire** [comment]
Fixed it !

V33.2 Working 😄 Thanks a lot !
![image](https://github.com/observerly/astrometry/assets/43670144/65366d49-5c2c-45f6-94ce-f1358681e701)
![image](https://github.com/observerly/astrometry/assets/43670144/bb8dee47-b207-451e-989f-292c6001707d)
